### ISSUE TITLE
oauthstate cookie expiration

### ISSUE THREAD

**Issue by dimalinux** [douglasmakey/oauth2-example#1]
Thank you for the excellent example!  I noticed that the _oauthstate_ cookie is configured for an entire year.  If I understand correctly, it's only needed for the time when the user is redirected to Google.  Would it make sense to adjust it down to 20 minutes or less?

**Comment by douglasmakey** [comment]
Hello, @dimalinux, thanks for the suggestion, I put a year just to test but I forgot to change that.
